### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by kaytrance** [needim/noty#419]
Trying to use noty in my react application, and on a build stage I am getting this error in terminal, and due to it build fails.
```
C:\Users\---\---\---\node_modules\noty\lib\noty.js:308
  if (typeof document.hidden !== 'undefined') {
  ^

ReferenceError: document is not defined
    at Object.visibilityChangeFlow (C:\Users\---\---\---\node_modules\noty\lib\noty.js:308:3)
    at Object.module.exports (C:\Users\---\---\---\node_modules\noty\lib\noty.js:2848:7)
    at __webpack_require__ (C:\Users\---\---\---\node_modules\noty\lib\noty.js:38:30)
    at Object.defineProperty.value (C:\Users\---\---\---\node_modules\noty\lib\noty.js:84:18)
    at C:\Users\---\---\---\node_modules\noty\lib\noty.js:87:10
    at webpackUniversalModuleDefinition (C:\Users\---\---\---\node_modules\noty\lib\noty.js:11:20)
    at Object.<anonymous> (C:\Users\---\---\---\node_modules\noty\lib\noty.js:18:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\---\---\---\build_server\Notify.js:12:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

And here's a content of `Notify.js` file on what build fails with above error:

```
import Noty from "noty";

const options = {
   text    : "",
   timeout : 3500,
   type    : "alert",
   killer  : true
};



class Notify {

   static ok(text) {
      return new Noty({
         ...options,
         type: "succeess",
         text
      }).show();
   }

   static error(text) {
      return new Noty({
         ...options,
         type: "error",
         text
      }).show();
   }

   static warn(text) {
      return new Noty({
         ...options,
         type: "warning",
         text
      }).show();
   }

}

export default Notify;
```

I am using `noty: 3.1.14` and `webpack: 3.0.0`

**Comment by kaytrance** [comment]
I think there should be some additional check in that `visibilityChangeFlow()` function whether `window` object even exists so to be able to use `noty` when doing server-side rendering.

**Comment by needim** [comment]
Thanks, I will fix that in next release. 👍

**Comment by needim** [comment]
Hi, @kaytrance. I'm adding a browser control for visibilityChangeFlow. 
But I think you should check this issue too: https://github.com/webpack/react-starter/issues/37

I'm gonna release v3.2.0-beta today. So, keep me updated, thanks.

**Comment by kenberkeley** [comment]
So any update about this issue after 2 years?
